#!/usr/bin/env bash

# nodejs-launcher - https://github.com/Yonle/nodejs-launcher
# A simple nodejs launcher that executes a latest nodejs binary

# Note: Only x86_64 or amd64 is supported

if [ $(uname -m) != "x86_64" ]; then
  echo "Sorry. This scripts only supports x86_64 or amd64 platform."
  exit 6
fi

export MAIN_DIR=${TMPDIR:-/tmp}/.nodejs-launcher

# Create main directory if there's none
[ ! -d $MAIN_DIR ] && mkdir $MAIN_DIR

# Get latest release from nodejs repo
# Reference: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c#gistcomment-2552690
export LATEST_RELEASE=$(curl -s "https://api.github.com/repos/nodejs/node/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
export DOWNLOAD_URL="https://nodejs.org/dist/${LATEST_RELEASE}/node-${LATEST_RELEASE}-linux-x64.tar.xz"
export __NODE_PATH=$(echo $MAIN_DIR/node-*/)

# Detect whenever node 16 binary is in ${TMPDIR:-/tmp} directory or no
if [ ! -x $__NODE_PATH/bin/node ]; then
  echo -n "[curl] Extracting node $LATEST_RELEASE.... "
  curl -sL $DOWNLOAD_URL | tar -Jxf - -C $MAIN_DIR
  [ $? != 0 ] && echo "[fail] Failed to Installing node $LATEST_RELEASE. Nake sure you have a stable network connection and try again later." && exit 6
  echo "Installed"

  # Re-export Variable
  export __NODE_PATH=$(echo $MAIN_DIR/node-*/)
fi

# These variable is required in order to load binaries & library from different path.
export LD_LIBRARY_PATH=$__NODE_PATH/lib:$LD_LIBRARY_PATH
export PATH=$__NODE_PATH/bin:${PATH:-/usr/bin}

# Run Node command
node $@
