#!/usr/bin/env bash

# nodejs-launcher - https://github.com/Yonle/nodejs-launcher
# A simple nodejs launcher that executes a latest nodejs binary

# Note: Only x64 is supported

if [ $(uname -m) != "x86_64" ]; then
  echo "Sorry. This project only supports x86_64 platform."
  exit 6
fi

if [ ! "$TMPDIR" ]; then
  export TMPDIR=/tmp
fi

if [ ! "$HOME" ]; then
  export HOME=/home
fi

export MAIN_DIR=$HOME/.nodejs-launcher

# Create main directory if there's none
if [ ! -d $MAIN_DIR ]; then
  mkdir $MAIN_DIR
fi

# Get latest release from nodejs repo
# Referenced at: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c#gistcomment-2552690
export LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/nodejs/node/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
export DOWNLOAD_URL="https://nodejs.org/dist/${LATEST_RELEASE}/node-${LATEST_RELEASE}-linux-x64.tar.xz"
export __NODE_PATH=$(echo $MAIN_DIR/node-*/)

# Detect whenever node 16 binary is in $TMPDIR directory or no
if [ ! -x $__NODE_PATH/bin/node ]; then
  echo "[curl] Downloading node v16.7.... "
  curl -L#o $TMPDIR/node.tar.xz $DOWNLOAD_URL
  # Extract the archive
  echo -n "[tar] Extracting.... "
  tar -xf $TMPDIR/node.tar.xz -C $MAIN_DIR && rm $TMPDIR/node.tar.xz
  echo "Done"
  # Re-export Variable
  export __NODE_PATH=$(echo $MAIN_DIR/node-*/)
  echo -n "[node] Got version: "
  $__NODE_PATH/bin/node --version
fi

export LD_LIBRARY_PATH=$__NODE_PATH/lib:$LD_LIBRARY_PATH
export PATH=$__NODE_PATH/bin:$PATH

# Run Node command
node $@
