
name: Run Installation 
on:
  push:
    branches:
    - master
    paths:
    - 'node'
  pull_request:
    branches:
    - master
    paths:
    - 'node'

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: ./node Hello-world.js
