
name: Run Installation & Tests
on:
  push:
    branches:
    - master
    paths:
    - 'node'
    - 'launch'
    - 'npm'
    - '.github/workflows/main.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'node'
    - 'npm'
    - 'launch'
    - '.github/workflows/main.yml'

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NodeJS
        run: ./node Hello-world.js
      - name: npm with better-sqlite3 installation test
        run: ./npm install better-sqlite3
